# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef7c27123ec84378a28dff827625e9549fbfefca75440ffba5917b6abaf62c3990db150ac00ce0bc6fdd865ba58374284e5682f5396a9c2e791561cd8147c38b

test:
  secret_key_base: 3523128f3f1b1b57eab255d5ce7be8d77cd428ad87e4df6c2505af7ff615c0cc47347fae04f22f3bcaa28d49ce3523c5e0747500f079daafa4e7bade23ca170e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
